Repository PrograMemo-Groom/teammate, pull requests merged in 2025-03, with the labels that each got.

#19 UserProfile 엔티티 및 API 구현
  src/main/java/teammate/teammate/controller/UserProfileController.java
  src/main/java/teammate/teammate/domain/UserProfile.java
  src/main/java/teammate/teammate/repository/UserProfileRepository.java
  src/main/java/teammate/teammate/service/UserProfileService.java
Labels: 기능추가

#22 상태메시지, 프로필 수정 화면의 버튼들 api 구현
  src/main/java/teammate/teammate/controller/UserProfileController.java
  src/main/java/teammate/teammate/domain/UserProfile.java
  src/main/java/teammate/teammate/service/UserProfileService.java
  src/main/resources/application.properties
Labels: 기능추가

#23 [디자인 추가] 페이지별 디자인 추가
  web/package-lock.json
  web/package.json
  web/src/App.jsx
  web/src/css/_global.scss
  web/src/css/pages/Home.module.scss
  web/src/css/pages/Profile.module.scss
  web/src/css/pages/Schedule.module.scss
  web/src/pages/Home.jsx
  web/src/pages/UserProfile.jsx
  web/src/pages/components/Schedule.jsx
  web/src/pages/components/TeamCalendar.jsx
  web/src/pages/components/Users.jsx
  web/yarn.lock
Labels: 기능추가

#31 ✨ 메인페이지 프로필 조회, 캘린더 월별로 조회, 캘린더 특정 날짜 조회, 팀 TodoList 조회
  src/main/java/teammate/teammate/controller/HomeController.java
  src/main/java/teammate/teammate/controller/MainController.java
  src/main/java/teammate/teammate/domain/CalendarEvents.java
  src/main/java/teammate/teammate/domain/Teams.java
  src/main/java/teammate/teammate/domain/Todos.java
  src/main/java/teammate/teammate/domain/Users.java
  src/main/java/teammate/teammate/repository/MainRepository.java
  src/main/java/teammate/teammate/service/HomeService.java
  src/main/java/teammate/teammate/service/MainService.java
Labels: 기능추가

#50 Be/sim ✨ Todo 추가, 수정, 삭제 기능
  src/main/java/teammate/teammate/controller/MainController.java
  src/main/java/teammate/teammate/controller/UserProfileController.java
  src/main/java/teammate/teammate/domain/Todos.java
  src/main/java/teammate/teammate/domain/UserProfile.java
  src/main/java/teammate/teammate/domain/Users.java
  src/main/java/teammate/teammate/repository/MainRepository.java
  src/main/java/teammate/teammate/repository/UserProfileRepository.java
  src/main/java/teammate/teammate/service/MainService.java
  src/main/java/teammate/teammate/service/UserProfileService.java
Labels: 기능추가

#54 ✨todo 삭제, 체크, 추가, 수정 기능 추가 + 캘린더 하단 일정view 컴포넌트 추가
  web/package-lock.json
  web/package.json
  web/src/App.jsx
  web/src/css/pages/Home.module.scss
  web/src/pages/Home.jsx
  web/src/pages/components/ScheduleView.jsx
  web/src/pages/components/TeamTodo.jsx
  web/src/store/Store.js
  web/src/store/reducer/TodoReducer.js
Labels: 기능추가

#55 Be/sim ✨ 일정 모달 CRUD 기능
  src/main/java/teammate/teammate/controller/MainController.java
  src/main/java/teammate/teammate/repository/MainRepository.java
  src/main/java/teammate/teammate/service/MainService.java
Labels: 기능추가

#66 프로필 수정에 필요한 기능 로직 추가
  build.gradle
  src/main/java/teammate/teammate/ProfileUpdateRequest.java
  src/main/java/teammate/teammate/controller/UserController.java
  src/main/java/teammate/teammate/controller/UserProfileController.java
  src/main/java/teammate/teammate/domain/UserProfile.java
  src/main/java/teammate/teammate/domain/Users.java
  src/main/java/teammate/teammate/repository/UserLinksRepository.java
  src/main/java/teammate/teammate/repository/UserProfileRepository.java
  src/main/java/teammate/teammate/repository/UserSkillsRepository.java
  src/main/java/teammate/teammate/service/UserProfileService.java
  src/main/java/teammate/teammate/service/UserService.java
  uploads/hong123_profile.png
  uploads/kimdev_profile3.jpg
  uploads/profile.png
  uploads/profile3.jpg
Labels: 기능추가

#77 Fe/jin ✨ 등록 버튼 기능 추가
  web/src/css/pages/Profile.module.scss
  web/src/css/pages/Schedule.module.scss
  web/src/pages/UserProfile.jsx
  web/src/pages/components/Schedule.jsx
  web/src/pages/components/TeamCalendar.jsx
Labels: 기능추가

#76 Be/sim ♻️ 캘린더 api 예외 처리, json 응답 객체 반환
  src/main/java/teammate/teammate/controller/ApiResponse.java
  src/main/java/teammate/teammate/controller/CalendarController.java
  src/main/java/teammate/teammate/exceptionHandler/GlobalExceptionHandler.java
  src/main/java/teammate/teammate/repository/CalendarRepository.java
  src/main/java/teammate/teammate/service/CalendarService.java
Labels: 리팩토링

#84 💡 테스트용 주석추가
  web/src/pages/components/Schedule.jsx
Labels: 수정필요x

#86 Be/sim ♻️ getUserByTeamCode json 응답과 예외처리
  src/main/java/teammate/teammate/controller/ApiResponse.java
  src/main/java/teammate/teammate/controller/UserController.java
  src/main/java/teammate/teammate/repository/UserRepositoryCustomImpl.java
  src/main/java/teammate/teammate/service/UserService.java
Labels: 리팩토링

#89 Be/sim ♻️ Todos 관련 로직 예외처리, 포매팅된 Json 객체 반환 처리
  src/main/java/teammate/teammate/controller/TodosController.java
  src/main/java/teammate/teammate/exceptionHandler/GlobalExceptionHandler.java
  src/main/java/teammate/teammate/repository/TodosRepository.java
  src/main/java/teammate/teammate/service/TodosService.java
Labels: 리팩토링

#92 프로필 부분 예외처리 수정
  src/main/java/teammate/teammate/ProfileUpdateRequest.java
  src/main/java/teammate/teammate/UserProfileResponse.java
  src/main/java/teammate/teammate/controller/UserController.java
  src/main/java/teammate/teammate/dto/ProfileUpdateRequest.java
  src/main/java/teammate/teammate/dto/UserProfileResponse.java
  src/main/java/teammate/teammate/service/UserService.java
Labels: 리팩토링

#91 Be/sim 🎨 응답 코드 변경, 날짜 검증 로직 추가
  src/main/java/teammate/teammate/controller/CalendarController.java
  src/main/java/teammate/teammate/service/TodosService.java
Labels: 버그

#93 🚨 getUserByTeamCode 코드 충돌로 인한 버그 수정
  src/main/java/teammate/teammate/service/UserService.java
Labels: 버그
